//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection.Emit;

namespace EF
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class GGN_NewsEntities : DbContext
    {
        public GGN_NewsEntities()
            : base("name=GGN_NewsEntities")
        {
            Database.SetInitializer(new CreateDatabaseIfNotExists<GGN_NewsEntities>());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //CodeFirst 方式
            //throw new UnintentionalCodeFirstException();
            //modelBuilder.Entity<TGame>().ToTable("TGame");
            //modelBuilder.Entity<TCategory>().ToTable("TCategory");
            Configuration.LazyLoadingEnabled = false;
            Configuration.ValidateOnSaveEnabled = false;
            Configuration.AutoDetectChangesEnabled = false;
        }

        public DbSet<TCategory> TCategory { get; set; }
        public DbSet<TGame> TGame { get; set; }
        public DbSet<TGameRCategory> TGameRCategory { get; set; }
    }
}
